"""followers

Revision ID: 6ba4215718df
Revises: 6f99224a0e12
Create Date: 2023-03-31 13:52:49.532319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba4215718df'
down_revision = '6f99224a0e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower', sa.Integer(), nullable=False),
    sa.Column('following', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower'], ['users.id'], name=op.f('fk_follow_follower_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following'], ['users.id'], name=op.f('fk_follow_following_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follow'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow')
    # ### end Alembic commands ###
