"""signups

Revision ID: 6bf1bcee685e
Revises: b08e218c7d90
Create Date: 2023-01-10 18:18:46.134402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf1bcee685e'
down_revision = 'b08e218c7d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sign_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.id'], name=op.f('fk_sign_ups_author_users')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_sign_ups_post_id_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sign_ups'))
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('sign_ups')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sign_ups', sa.INTEGER(), nullable=True))

    op.drop_table('sign_ups')
    # ### end Alembic commands ###
