"""rmvdatefromsignup

Revision ID: e1e6c56bfffd
Revises: 6bf1bcee685e
Create Date: 2023-01-10 18:22:48.968680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e6c56bfffd'
down_revision = '6bf1bcee685e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sign_ups', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sign_ups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
